# Generated by Django 3.2.5 on 2021-07-20 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='mode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('password', models.CharField(max_length=70)),
                ('email', models.EmailField(max_length=70)),
                ('contact', models.IntegerField(max_length=70)),
            ],
        ),
    ]
